title: artur kulmizev
baseurl: ""
url: "http://rutrastone.github.io"

markdown: kramdown

tracking_id: #

footer: no
footer_url: "https://akulmizev.com"
footer_text: "Artur Kulmizev"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "about"
   link: "index"
 - name: "cv"
   link: "ak_cv.pdf"
 - name: "contact"
   link: "contact"
 - name: "supernlp"
   link: "https://supernlp.github.io"
