title: Artur Kulmizev
baseurl: "/"
url: "http://rutrastone.github.io"

markdown: kramdown

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "CV"
   link: "ak_cv.pdf"
 - name: "Contact"
   link: "contact"
